matrix:
  include:
    - language: c
      
      before_install:
        - sudo apt-get install -y rpm
        - sudo apt-get install -y valgrind
        - sudo apt-get install -y libevent-dev
        - sudo apt-get install -y librabbitmq-dev
        - sudo apt-get install -y subversion

        #  install matrix library
        - svn checkout https://github.com/Horardrim/matrix_c/trunk/rpmbuild/SOURCES/
        - tar -zxvf SOURCES/hm-matrix-c-1.0.0.tar.gz
        - cd hm-matrix-c-1.0.0
        - export MATRIX_C_VERSION=`grep "define MATRIX_C_VERSION" version.h | awk -F "\"" '{print $2}'`
        - make
        - sudo cp ../output/libhm-matrix-c.so.1.0.0 /lib/x86_64-linux-gnu/
        - sudo ln -s  /lib/x86_64-linux-gnu/libhm-matrix-c.so.1.0.0  /lib/x86_64-linux-gnu/libhm-matrix-c.so
        - sudo mkdir /usr/include/matrix-c
        - sudo cp *.h /usr/include/matrix_c

      script:
        - make cov
        - make test
        - make gencov

      after_success:
        - bash <(curl -s https://codecov.io/bash)
